[package]
name = "zen"
version = "0.2.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
lazy_static = "1.4.0"
nom = "^7.1.1"